### ISSUE TITLE
[GSoC] Update LibreCores CI Docker to newer tool versions 

### ISSUE THREAD

**Issue by Nancy-Chauhan** [librecores/docker-images#10]
**Goal** : This issue is in reference with one of the first project goal of GSoC 2019 Project for Setting up Demo CI Flow for mor1kx Project : https://github.com/openrisc/mor1kx 
The mor1kx pipelines are constantly verified for correctness with the or1k Continuous Integration (CI) suite running in travis ci : https://github.com/openrisc/mor1kx/blob/master/.travis.yml . It is proposed to use Librecores CI for Continous Integration of mor1kx .

**Implementation :** Updating the Librecores CI Docker image to newer tool versions so that it can be used in mor1kx project by running tests [mor1kx scripts](https://github.com/openrisc/mor1kx/tree/master/.travis ) on the [LibreCores CI ](https://github.com/librecores/docker-images/tree/master/librecores-ci)Docker image 
 

CC @oleg-nenashev @wallento @stffrdhrn
[_Link to doc proposal_ ](https://docs.google.com/document/d/1d0mIrLpU80IqB5oe4CvUz5H3bMR84tg0P99doWrovek/edit)

**Comment by oleg-nenashev** [comment]
https://github.com/librecores/docker-images/pull/6 should partially address the story
