### ISSUE TITLE
[GSoC 2019] Create docker image for openrisc based on the standard librecores/librecores-ci image

### ISSUE THREAD

**Issue by Nancy-Chauhan** [librecores/docker-images#19]
Docker image for [openrisc](https://github.com/openrisc) can be created for using it for Continous Integration of openrisc projects such as mor1kx and or1k_marocchino , targetting specific tools used by openrisc Projects

**Comment by oleg-nenashev** [comment]
@Nancy-Chauhan Please do not forget to close the issues here.
BTW, is the repository ready to be released? If so, will do it

**Comment by Nancy-Chauhan** [comment]
@oleg-nenashev This is fine! but once I make PR in the mor1kx repository with changes in Jenkinsfile, which uses the librecores-ci-openrisc docker image, we can be sure about this docker image then and we can release it then
