### ISSUE TITLE
Provide overview of available images on the README page

### ISSUE THREAD

**Issue by oleg-nenashev** [librecores/docker-images#31]
We have several images with embedded documentation, but we do not really have top-level documentation so that LCCI users can find the right image. We should write some.

- [ ] There is a list of all images in the repository
- [ ] For each image there are few sentences describing what they do

**Comment by Evalle** [comment]
I can take care of it.

**Comment by oleg-nenashev** [comment]
thanks!

**Comment by oleg-nenashev** [comment]
Done in #34
