### ISSUE TITLE
Provide tagged version of librecores/librecores-ci on Docker Hub

### ISSUE THREAD

**Issue by imphil** [librecores/docker-images#4]
To enable users choosing from a specific base images for their tests we should provide tagged versions of the librecores-ci images on Docker Hub (e.g. 2017.1). Currently, only the "latest" tag is available (https://hub.docker.com/r/librecores/librecores-ci/tags/).

**Comment by oleg-nenashev** [comment]
Done

**Comment by oleg-nenashev** [comment]
We should get tags once https://github.com/librecores/docker-images/issues/21 is fixed
